version: "3"

services:
  chatgpt-discord-bot:
    build: .
    image: chatgpt-discord-bot
    container_name: chatgpt-discord-bot
    volumes:
      - /docker/chatgpt-discord-bot/.env:/DiscordBot/.env